Options.Triggers.push({
  zoneId: ZoneId.TheOmegaProtocolUltimate,
  timelineReplace: [
    {
      //   locale: "cn",
      missingTranslations: true,
      replaceSync: {
        "Engage!": "(?:战斗开始！|Engage!|戦闘開始！)",
        "戦闘開始！": "(?:战斗开始！|Engage!|戦闘開始！)",
        "Omega": "[^:]+",
        "オメガ": "[^:]+",
        "Erichthonios": "[^:]+",
        "エリクトニオス": "[^:]+",
        "Alpha Omega": "[^:]+",
        "cosmo meteor": "[^:]+",
        "cosmo meteors": "[^:]+",
        "cosmo comet": "[^:]+",
        "cosmo comets": "[^:]+",
        "アルファオメガ": "[^:]+",
        "コスモメテオ": "[^:]+",
        "コスモコメット": "[^:]+",
        "アルファオメガ": "[^:]+",
        "コスモメテオ": "[^:]+",
        "コスモコメット": "[^:]+",
      },
      replaceText: {
        "Atomic Ray": "原子射线",
        "(?<! )Explosion": "爆炸",
        "Unmitigated Explosion": "大爆炸",
        "Solar Ray": "太阳射线",
        "Program Loop": "循环程序",
        "Storage Violation ?(?!Obliteration)": "清除记忆污染S",
        "Storage Violation Obliteration": "引爆记忆污染",
        "Blaster": "冲击波",
        "Pantokrator": "全能之主",
        "Ballistic Impact": "导弹命中P",
        "Flame Thrower": "火炎放射",
        "Guided Missile Kyrios": "跟踪导弹P",
        "Condensed Wave Cannon Kyrios": "大功率波动炮P",
        "Diffuse Wave Cannon Kyrios": "扩散波动炮P",
        "(?<! )Wave Cannon Kyrios": "波动炮P",
        "Subject Simulation F": "变形F",
        "Subject Simulation M": "变形M",
        "Optical Laser": "光学射线F",
        "Cosmo Memory": "宇宙记忆",
        "Beyond Strength": "盾连击G",
        "Efficient Bladework": "剑击",
        "Beyond Defense": "盾连击S",
        "Pile Pitch": "能量投射",
        "Superliminal Steel": "剑连击B",
        "Optimized Blizzard III": "欧米茄冰封",
        "Discharger": "能量放出",
        "Optimized Fire III": "欧米茄烈炎",
        "Spotlight": "聚光灯",
        "Optimized Meteor": "欧米茄陨石流星",
        "Optimized Sagittarius Arrow": "欧米茄射手天箭",
        "Optimized Bladedance": "欧米茄刀光剑舞",
        "Limitless Synergy": "协作程序LB",
        "Party Synergy": "协作程序PT",
        "Firewall": "防御程序",
        "Optimized Passage of Arms": "欧米茄通道",
        "Laser Shower": "激光骤雨",
        "Ion Efflux": "离子流出",
        "Colossal Blow": "巨能爆散",
        "Wave Repeater": "速射式波动炮",
        "(?<! )Sniper Cannon": "狙击式波动炮",
        "High\\-powered Sniper Cannon": "狙击式高输出波动炮",
        "Hello, World": "你好，世界",
        "Critical Synchronization Bug": "严重错误：同步",
        "Critical Overflow Bug": "严重错误：上溢",
        "Latent Synchronization Defect": "潜在错误：同步",
        "Latent Defect": "潜在错误",
        "Critical Underflow Bug": "严重错误：下溢",
        "Critical Performance Bug": "严重错误：性能",
        "Cascading Latent Defect": "潜在错误：下溢",
        "Latent Performance Defect": "潜在错误：性能",
        "Patch": "补丁",
        "Critical Error": "严重错误",
        "Oversampled Wave Cannon": "探测式波动炮",
        "Hyper Pulse": "超能脉冲",
        "(?<! )SWave Cannon": "波动炮",
        "Diffuse Wave Cannon": "扩散波动炮",
        "Blue Screen": "停止错误",
        "Blind Faith": "盲目信仰",
        "Run: \\*\\*\\*\\*mi\\* \\(Delta Version\\)": "代号：＊能＊·德尔塔",
        "Hello, Near World": "你好，世界：近",
        "Peripheral Synthesis": "生成外设",
        "Rear Lasers": "背环激光",
        "Swivel Cannon": "旋回式波动炮",
        "Run: \\*\\*\\*\\*mi\\*$": "代号：＊能＊",
        "Cosmo Arrow": "宇宙之箭",
        "Cosmo Dive": "宇宙俯冲",
        "Unlimited Wave Cannon": "波动炮限制器减档",
        "^Wave Cannon": "波动炮",
        "\\(stacks\\)": "分摊",
        "Cosmo Meteor": "宇宙流星",
        "Magic Number": "不明常数",
        "Synthetic Shield": "合成盾",
        "Archive Peripheral": "手臂归档",
        "Run: \\*\\*\\*\\*mi\\* \\(Sigma Version\\)": "代号：＊能＊·西格玛",
        "Run: \\*\\*\\*\\*mi\\* \\(Omega Version\\)": "代号：＊能＊·欧米茄",
        "Hello, Distant World": "你好，世界：远",
        "Run: \\*\\*\\*\\*mi\\* \\(Psiscape Version\\)": "代号：＊能＊·普西",
        "コード：＊＊＊ミ＊【プサイ】": "代号：＊能＊·普西",
      },
    },
  ],
});
