Options.Triggers.push({
  id: "SoumaTheAbyssalFractureExtreme",
  zoneId: ZoneId.TheAbyssalFractureExtreme,
  timelineReplace: [
    {
      locale: "cn",
      missingTranslations: true,
      replaceSync: {
        "Comet": "[^:]+",
        "Toxic Bubble": "[^:]+",
        "Zeromus": "[^:]+",
      },
      replaceText: {
        "Abyssal Echoes": "深渊之韵",
        "Abyssal Nox": "深渊之夜",
        "Akh Rhai": "天光轮回",
        "Big Bang": "大爆炸",
        "Big Crunch": "大坍缩",
        "Black Hole": "黑洞",
        "Branding Flare": "核爆烙印",
        "Burst": "飞散",
        "Bury": "塌方",
        "Chasmic Nails": "深渊之爪",
        "Dark Matter": "暗物质",
        "Dimensional Surge": "维度涌动",
        "Explosion": "爆炸",
        "(?<! )Flare": "核爆",
        "Flow of the Abyss": "深渊之流",
        "Forked Lightning": "叉形闪电",
        "Fractured Eventide": "黑龙闪",
        "Meteor Impact": "陨石冲击",
        "Miasmic Blast": "瘴气爆发",
        "Nostalgia": "望乡",
        "Primal Roar": "大咆哮",
        "Prominence Spine": "突出脊柱",
        "Rend the Rift": "次元干涉",
        "Sable Thread": "漆黑射线",
        "Sparking Flare": "核爆火花",
        "Umbral Prism": "暗之重波",
        "Umbral Rays": "暗之波动",
        "Visceral Whirl": "脏腑之旋",
        "Void Bio": "虚空毒菌",
        "Void Meteor": "虚空陨石",
        "the Dark Beckons": "黑暗侵蚀：吸引",
        "the Dark Binds": "黑暗侵蚀：锁链",
        "the Dark Divides": "黑暗侵蚀：分离",
      },
    },
  ],
});
