Options.Triggers.push({
  id: 'SoumaEverkeepExtreme',
  zoneId: ZoneId.EverkeepExtreme,
  timelineReplace: [
    {
      'locale': 'en',
      'replaceSync': {
        'Fang': '[^:]+',
        'Zoraal Ja': '[^:]+',
      },
      'replaceText': {
        'Fiery Edge/Stormy Edge': 'Fiery/Stormy Edge',
        'Forward Edge/Backward Edge': 'Forward/Backward Edge',
        'Siege of Vollok/Walls of Vollok': 'Siege/Walls of Vollok',
        'Actualize': '实现化',
        'Aero III': '暴风',
        'Backward Edge': '后退刃',
        'Bitter Whirlwind': '苦涩之风',
        'Blade Warp': '召唤刃',
        'Burning Chains': '火焰链',
        'Chasm of Vollok': '凶残之坑',
        'Dawn of an Age': '黎明纪元',
        'Drum of Vollok': '凶残之击',
        'Duty\'s Edge': '职责之刃',
        'Fiery Edge': '火焰刃',
        'Forged Track': '刃轨',
        'Forward Edge': '前锋刃',
        'Greater Gateway': '通道赋予',
        'Half Circuit': '自在巡回',
        'Half Full': '自在之力',
        'Multidirectional Divide': '多重通道',
        'Projection of Triumph': '投影刃',
        'Projection of Turmoil': '投影爆发',
        'Regicidal Rage': '弑君',
        'Siege of Vollok': '凶残之环',
        'Stormy Edge': '风刃',
        'Sync(?![-h])': '同步',
        '(?<! )Vollok': '刃·凶残',
        'Walls of Vollok': '凶残之圆',
      },
    },
    {
      'locale': 'de',
      'missingTranslations': true,
      'replaceSync': {
        'Fang': 'Reißzahn',
        'Zoraal Ja': 'Zoraal Ja',
      },
      'replaceText': {
        '\\(cast\\)': '(wirken)',
        '\\(damage\\)': '(Schaden)',
        '\\(enrage\\)': '(Finalangriff)',
        '\\(lines drop\\)': '',
        'Actualize': '实现化A',
        'Aero III': '暴风',
        'Backward Edge': '后退刃',
        'Bitter Whirlwind': '苦涩之风',
        'Blade Warp': '召唤刃',
        'Burning Chains': '火焰链',
        'Chasm of Vollok': '凶残之坑',
        'Dawn of an Age': '黎明纪元',
        'Drum of Vollok': '凶残之击',
        'Duty\'s Edge': '职责之刃',
        'Fiery Edge': '火焰刃',
        'Forged Track': '刃轨',
        'Forward Edge': '前锋刃',
        'Greater Gateway': '通道赋予',
        'Half Circuit': '自在巡回',
        'Half Full': '自在之力',
        'Multidirectional Divide': '多重通道',
        'Projection of Triumph': '投影刃',
        'Projection of Turmoil': '投影爆发',
        'Regicidal Rage': '弑君',
        'Siege of Vollok': '凶残之环',
        'Stormy Edge': '风刃',
        'Sync(?![-h])': '同步',
        '(?<! )Vollok': '刃·凶残',
        'Walls of Vollok': '凶残之圆',
      },
    },
    {
      'locale': 'fr',
      'missingTranslations': true,
      'replaceSync': {
        'Fang': 'crochet',
        'Zoraal Ja': 'Zoraal Ja',
      },
      'replaceText': {
        'Actualize': '实现化',
        'Aero III': '暴风',
        'Backward Edge': '后退刃',
        'Bitter Whirlwind': '苦涩之风',
        'Blade Warp': '召唤刃',
        'Burning Chains': '火焰链',
        'Chasm of Vollok': '凶残之坑',
        'Dawn of an Age': '黎明纪元',
        'Drum of Vollok': '凶残之击',
        'Duty\'s Edge': '职责之刃',
        'Fiery Edge': '火焰刃',
        'Forged Track': '刃轨',
        'Forward Edge': '前锋刃',
        'Greater Gateway': '通道赋予',
        'Half Circuit': '自在巡回',
        'Half Full': '自在之力',
        'Multidirectional Divide': '多重通道',
        'Projection of Triumph': '投影刃',
        'Projection of Turmoil': '投影爆发',
        'Regicidal Rage': '弑君',
        'Siege of Vollok': '凶残之环',
        'Stormy Edge': '风刃',
        'Sync(?![-h])': '同步',
        '(?<! )Vollok': '刃·凶残',
        'Walls of Vollok': '凶残之圆',
      },
    },
    {
      'locale': 'ja',
      'missingTranslations': true,
      'replaceSync': {
        'Fang': '[^:]+',
        'Zoraal Ja': '[^:]+',
      },
      'replaceText': {
        'Actualize': '实现化',
        'Aero III': '暴风',
        'Backward Edge': '后退刃',
        'Bitter Whirlwind': '苦涩之风',
        'Blade Warp': '召唤刃',
        'Burning Chains': '火焰链',
        'Chasm of Vollok': '凶残之坑',
        'Dawn of an Age': '黎明纪元',
        'Drum of Vollok': '凶残之击',
        'Duty\'s Edge': '职责之刃',
        'Fiery Edge': '火焰刃',
        'Forged Track': '刃轨',
        'Forward Edge': '前锋刃',
        'Greater Gateway': '通道赋予',
        'Half Circuit': '自在巡回',
        'Half Full': '自在之力',
        'Multidirectional Divide': '多重通道',
        'Projection of Triumph': '投影刃',
        'Projection of Turmoil': '投影爆发',
        'Regicidal Rage': '弑君',
        'Siege of Vollok': '凶残之环',
        'Stormy Edge': '风刃',
        'Sync(?![-h])': '同步',
        '(?<! )Vollok': '刃·凶残',
        'Walls of Vollok': '凶残之圆',
      },
    },
    {
      'locale': 'cn',
      'missingTranslations': true,
      'replaceSync': {
        'Fang': '[^:]+',
        'Zoraal Ja': '[^:]+',
      },
      'replaceText': {
        // '\\(cast\\)': '(wirken)',
        '\\(damage\\)': '(判定)',
        // '\\(enrage\\)': '(Finalangriff)',
        '\\(lines drop\\)': '',
        'Actualize': '实现化',
        'Aero III': '暴风',
        'Backward Edge': '后退刃',
        'Bitter Whirlwind': '苦涩之风',
        'Blade Warp': '召唤刃',
        'Burning Chains': '火焰链',
        'Chasm of Vollok': '凶残之坑',
        'Dawn of an Age': '黎明纪元',
        'Drum of Vollok': '凶残之击',
        'Duty\'s Edge': '职责之刃',
        'Fiery Edge': '火焰刃',
        'Forged Track': '刃轨',
        'Forward Edge': '前锋刃',
        'Greater Gateway': '通道赋予',
        'Half Circuit': '自在巡回',
        'Half Full': '自在之力',
        'Multidirectional Divide': '多重通道',
        'Projection of Triumph': '投影刃',
        'Projection of Turmoil': '投影爆发',
        'Regicidal Rage': '弑君',
        'Siege of Vollok': '凶残之环',
        'Stormy Edge': '风刃',
        'Sync(?![-h])': '同步',
        '(?<! )Vollok': '刃·凶残',
        'Walls of Vollok': '凶残之圆',
      },
    },
  ],
});
