Options.Triggers.push({
  zoneId: ZoneId.AsphodelosTheSecondCircleSavage,
  timelineReplace: [
    {
      missingTranslations: true,
      replaceSync: {
        "Engage!": "(?:战斗开始！|Engage!|戦闘開始！)",
        "戦闘開始！": "(?:战斗开始！|Engage!|戦闘開始！)",
        "Hippokampos": "[^:]+",
        "ヒッポカムポス": "[^:]+",
      },
      replaceText: {
        "Channeling Flow": "第一次普通对冲",
        "チャネリングフロウ": "第一次普通对冲",
        "Channeling Overflow": "对冲 长短分组",
        "チャネリングオーバーフロウ": "对冲 长短分组",
        "Coherence(?! [FL])": "距离衰减+直线分摊",
        "コヒーレンス(?! .)": "距离衰减+直线分摊",
        "Crash": "冲撞",
        "衝突": "冲撞",
        "Deadly Current": "激流冲",
        "激流衝": "激流冲",
        "Dissociation": "头尾分离+俯冲",
        "ディソシエーション": "头尾分离+俯冲",
        "Doubled Impact": "分摊死刑",
        "ダブルインパクト": "分摊死刑",
        "Great Typhoon": "对冲",
        "荒波": "对冲",
        "Hard Water": "硬水块",
        "重水塊": "硬水块",
        "Kampeos Harma": "麻将",
        "カンペオスハルマ": "麻将",
        "Murky Depths": "AOE",
        "マーキーディープ": "AOE",
        "Ominous Bubbling": "双H分摊",
        "霊水弾": "双H分摊",
        "Predatory Avarice": "被点远离,H分摊",
        "多重刻印": "被点远离,H分摊",
        "Sewage Deluge": "大AOE",
        "スウェッジデリージュ": "大AOE",
        "Sewage Eruption": "三连黄圈",
        "スウェッジエラプション": "三连黄圈",
        "Shockwave": "跳跃击退",
        "ショックウェーブ": "跳跃击退",
        "Spoken Cataract": "真头",
        "ブレス＆カタラクティス": "真头",
        "Tainted Flood": "红圈散开",
        "テインテッドフラッド": "红圈散开",
        "Winged Cataract": "假头",
        "ウィング＆カタラクティス": "假头",
        "Coherence Flare": "核爆",
        "Coherence Line": "挡枪",
        "untargetable": "不可选中",
        "ターゲット不可": "不可选中",
        "(?<=--)targetable": "可选中",
        "ターゲット可能": "可选中",

        "沟流充溢": "普通对冲",
        "沟流溢出": "对冲 长短分组",
        "连贯攻击": "接线核爆+分摊",
        // '连贯攻击 (核爆)':"",
        // '连贯攻击 (分摊)':"",
        // '冲撞':"",
        // '激流冲':"",
        // '分离':"",
        // '分离 (冲锋)':"",
        "双重冲击": "分摊死刑",
        // '荒波':"",
        // '重水块':"",
        "海怪战车": "麻将",
        "深度污浊": "AOE",
        "灵水弹": "分摊",
        "灵水弹 (分组)": "分摊（分组）",
        "多重刻印": "被点远离,H分摊",
        "活饵的刻印": "孤独感",
        "污水泛滥": "大AOE",
        "污水喷发": "三连黄圈",
        "震荡波": "跳跃击退",
        "吐息飞瀑": "真头",
        "污染洪水": "6人红圈",
        "展翅飞瀑": "假头",
      },
    },
  ],
  triggers: [
    {
      id: "2层没有，占坑防止有人总问",
      disabled: true,
      netRegex: new RegExp(),
      alertText: `？`,
    },
  ],
});
